version: '3'
services:
  agent:
    image: dev
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
      - ./logs:/app/logs
    #ports:
      #- 0.0.0.0:6006:6006
    #command: python -m pytest test_agent.py::TestAgent::test_SpaceInvaders_v0
    #command: ls && sleep 100
  source_dev:
    image: source_dev
    build:
      context: .
      dockerfile: test.Dockerfile
    volumes:
      - .:/app
      - ./logs:/app/logs
  board:
    image: tensorflow/tensorflow:latest-gpu-py3
    volumes:
      - ./logs:/logs
      - ./logs:/app/logs
    ports:
      - 0.0.0.0:6006:6006
    command: tensorboard --logdir=/logs --bind_all

