version: '3'
services:
  agent:
    build: .
    volumes:
      - .:/app
    command: python /app/main.py
  tensorboard:
    image: tensorflow/tensorflow
    volumes:
    - ./logs:/logs
    ports:
      - "6006:6006"
    expose:
      - "6006"
    command: tensorboard --logdir /logs
