version: '3'
services:
  agent:
    build: .
    volumes:
      - .:/app
      - ./logs:/app/logs
    #ports:
      #- 0.0.0.0:6006:6006
    command: python main.py
  board:
    image: tensorflow/tensorflow:latest-py3
    volumes:
      - ./logs:/logs
    ports:
      - 0.0.0.0:6006:6006
    command: tensorboard --logdir=logs --bind_all

